# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WDDX
version:      1.02
version_from: WDDX.pm
installdirs:  site
requires:
    Carp:                          0
    MIME::Base64:                  0
    Time::Local:                   0
    XML::Parser:                   2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
